### ISSUE TITLE
Unable to create/access favorite servers

### ISSUE THREAD

**Issue by benjamw** [yoichiro/chrome_mysql_admin#50]
Since the update, I'm no longer able to create and/or access favorite servers.

The list of favorite servers that I had before the update is gone, and I'm unable to create any new favorites. I'm not sure if it's creating them and I just can't see them, or if they are not being created.

Let me know if you need any other information.

**Note**: I get this in my console log for window.html:

extensions::platformApp:15 history.pushState is not available in packaged apps.
extensions::platformApp:15 history.state is not available in packaged apps.

**Comment by benjamw** [comment]
And this error when I try to save a favorite:

2016-02-15 21:58:45.179 extensions::lastError:133 Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.
    at Object.callback (chrome-extension://ndgnpnpakfcdjmpgmcaknimfgcldechn/scripts/window/services/favorite_service.js:45:37)reportIfUnchecked @ extensions::lastError:133

**Comment by DaavisGit** [comment]
I'm trying to save a new favorite connection and this is what I get :
Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at Object.callback (chrome-extension://---/scripts/window/services/favorite_service.js:45:37)
